# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialogs\bd_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class MyDelegate(QtWidgets.QItemDelegate):

    def createEditor(self, *args):
        return None


class Bd_view(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 800)

        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.delete_all = QtWidgets.QPushButton(Dialog)
        self.delete_all.setFont(font)
        self.delete_all.setObjectName("delete_all")
        self.delete.setFont(font)
        self.delete.setObjectName("delete")
        self.horizontalLayout.addWidget(self.delete)
        self.horizontalLayout.addWidget(self.delete_all)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setShowGrid(True)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        self.table.setRowCount(0)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setStretchLastSection(False)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.table.setSortingEnabled(True)
        self.verticalLayout.addWidget(self.table)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setFont(font)
        self.verticalLayout.addWidget(self.accept_button)
        self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table.setHorizontalHeaderLabels(['Логин', 'Пароль', 'Примечания'])
        self.table.verticalHeader().setSectionsClickable(False)
        self.table.setItemDelegateForColumn(0, MyDelegate())
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.delete.setText(_translate("Dialog", "Удалить"))
        self.accept_button.setText(_translate('Dialog', 'Назад'))
        self.delete_all.setText(_translate('Dialog', 'Удалить всё'))
        self.add.setText(_translate('Dialog', 'Добавить'))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Bd_view()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
